name = sulphur_update
title = Sulphur Update
description = Sulphur, Sulphur Slime, cinnabar, geysers, and sulphur smoke for BetterCraft.
author = wrxxnch
version = 1.0.0
license = MIT
depends = mcl_core, mcl_mobs, mcl_potions, mcl_trees, mcl_nether, mcl_buckets, mcl_jukebox
optional_depends = mcl_worlds, mcl_mapgen, mcl_spawn
